# Generated by Django 5.1.1 on 2024-09-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "performance")},
        ),
    ]
