# Generated by Django 5.1.1 on 2024-09-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
    ]
