# Generated by Django 5.1.1 on 2024-09-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(null=True, upload_to="play_image_file_path"),
        ),
    ]
